//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicio.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Orders = new HashSet<Orders>();
            this.Shipments = new HashSet<Shipments>();
            this.ShoppingCart = new HashSet<ShoppingCart>();
            this.Total_Users = new HashSet<Total_Users>();
        }
    
        public int customer_user_id { get; set; }
        public string customer_name { get; set; }
        public string customer_first_last_name { get; set; }
        public string customer_last_name { get; set; }
        public string customer_id { get; set; }
        public string customer_phone { get; set; }
        public string customer_email { get; set; }
        public System.DateTime customer_registration_date { get; set; }
        public System.DateTime customer_birthDate { get; set; }
        public string customer_photo { get; set; }
        public string customer_address { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shipments> Shipments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShoppingCart> ShoppingCart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Total_Users> Total_Users { get; set; }
    }

    public class Respuesta
    {
        public int Id { get; set; }
        public string Message { get; set; }
        public bool transaccion { get; set; }
        public Customer customer { get; set; }
        public List<Customer> customers { get; set; }
    }
}
