//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicio.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Total_Users = new HashSet<Total_Users>();
        }
    
        public int employee_user_id { get; set; }
        public string employee_name { get; set; }
        public string employee_first_last_name { get; set; }
        public string employee_second_last_name { get; set; }
        public string employee_id { get; set; }
        public string employee_phone { get; set; }
        public string employee_email { get; set; }
        public byte[] employee_hire_date { get; set; }
        public System.DateTime employee_birthDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Total_Users> Total_Users { get; set; }
    }
}
