//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicio.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERRORES
    {
        public int ID_ERROR { get; set; }
        public int ERROR_NUMBER { get; set; }
        public int ERROR_STATE { get; set; }
        public int ERROR_SEVERITY { get; set; }
        public int ERROR_LINE { get; set; }
        public string ERROR_PROCEDURE { get; set; }
        public string ERROR_MESSAGE { get; set; }
        public System.DateTime ERROR_DATETIME { get; set; }
    }
}
