//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicio.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERRORES
    {
        public int ID_ERROR { get; set; }
        public int ERROR_NUMBER { get; set; }
        public int ERROR_STATE { get; set; }
        public int ERROR_SEVERITY { get; set; }
        public int ERROR_LINE { get; set; }
        public string ERROR_PROCEDURE { get; set; }
        public string ERROR_MESSAGE { get; set; }
        public System.DateTime ERROR_DATETIME { get; set; }
    }
}
