//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicio.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string First_last_name { get; set; }
        public string Second_last_name { get; set; }
        public string Identification { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public System.DateTime Registration_date { get; set; }
        public Nullable<System.DateTime> Modification_date { get; set; }
        public System.DateTime Birth_date { get; set; }
        public string Address { get; set; }
        public Nullable<bool> Email_Verification { get; set; }
        public Nullable<System.Guid> Activation_Code { get; set; }
        public Nullable<int> User_Id { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
