//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicio.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipments
    {
        public int shipment_id { get; set; }
        public int shipment_order_id { get; set; }
        public System.DateTime shipment_date { get; set; }
        public string shipment_status { get; set; }
        public string shipment_address { get; set; }
        public string shipment_city { get; set; }
        public string shipment_state { get; set; }
        public string shipment_zip_code { get; set; }
        public string shipment_country { get; set; }
        public string shipment_phone { get; set; }
        public string shipment_email { get; set; }
        public System.Guid shipment_customer_id { get; set; }
    
        public virtual Orders Orders { get; set; }
        public virtual Users Users { get; set; }
    }
}
