//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicio.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipments
    {
        public int shipment_id { get; set; }
        public int shipment_order_id { get; set; }
        public byte[] shipment_date { get; set; }
        public string shipment_status { get; set; }
        public string shipment_address { get; set; }
        public string shipment_city { get; set; }
        public string shipment_state { get; set; }
        public string shipment_zip_code { get; set; }
        public string shipment_country { get; set; }
        public string shipment_phone { get; set; }
        public string shipment_email { get; set; }
        public int shipment_customer_id { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
