//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicio.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingCart
    {
        public int shoppingCart_id { get; set; }
        public int shoppingCart_customer_id { get; set; }
        public int shoppingCart_product_id { get; set; }
        public string shoppipingCart_product_name { get; set; }
        public string shoppingCart_image { get; set; }
        public string shoppingCart_description { get; set; }
        public int shoppingCart_quantity { get; set; }
        public decimal shoppingCart_product_price { get; set; }
        public string shoppingCart_state { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Product Product { get; set; }
    }
}
