//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicio.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCustomer
    {
        public int user_Id { get; set; }
        public string login_name_customer { get; set; }
        public string password_hash_customer { get; set; }
        public string name { get; set; }
        public string first_last_name { get; set; }
        public string second_last_name { get; set; }
        public int Id { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public System.DateTime registration_date { get; set; }
        public System.DateTime birth_date { get; set; }
        public string customer_photo { get; set; }
        public string address { get; set; }
    }
}
